In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
raw_data = pd.read_csv("../data/raw/diabetic_data.csv", keep_default_na=False, na_values=["?"], low_memory=False)

### Drop columns that exceed the 20% acceptable threshold for missing values

In [3]:
raw_data = raw_data.drop(columns=["weight", "payer_code", "medical_specialty"], inplace=False)

raw_data.head()

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),6,25,1,1,41,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,59,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,11,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),1,1,7,2,44,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),1,1,7,1,51,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

### Drop rows that exceed the 20% acceptable threshold for missing values.

In [4]:
threshold = raw_data.shape[1] * 0.2

rows_to_drop = raw_data[raw_data.isnull().sum(axis=1) > threshold].shape[0]
rows_to_keep = raw_data.shape[0] - rows_to_drop

print(f"Total rows: {raw_data.shape[0]}")
print(f"Rows to drop (>20% missing): {rows_to_drop}")
print(f"Rows to keep: {rows_to_keep}")

Total rows: 101766
Rows to drop (>20% missing): 0
Rows to keep: 101766

Since no rows have more than 20% missing we don't do anything

### Drop drug columns that are near constant (>= 99%).

In [5]:
DRUG_COLS = [
    "metformin","repaglinide","nateglinide","chlorpropamide","glimepiride",
    "acetohexamide","glipizide","glyburide","tolbutamide","pioglitazone",
    "rosiglitazone","acarbose","miglitol","troglitazone","tolazamide",
    "examide","citoglipton","insulin","glyburide-metformin","glipizide-metformin",
    "glimepiride-pioglitazone","metformin-rosiglitazone","metformin-pioglitazone"
]

drug_summary = raw_data[DRUG_COLS].apply(pd.Series.value_counts).T.fillna(0).astype(int)
drug_percentages = drug_summary.div(drug_summary.sum(axis=1), axis=0) * 100
  
drug_percentages

                               Down          No     Steady         Up
metformin                  0.565022   80.358862  18.027632   1.048484
repaglinide                0.044219   98.487707   1.359983   0.108091
nateglinide                0.010809   99.309200   0.656408   0.023584
chlorpropamide             0.000983   99.915492   0.077629   0.005896
glimepiride                0.190633   94.899082   4.588959   0.321325
acetohexamide              0.000000   99.999017   0.000983   0.000000
glipizide                  0.550282   87.534147  11.158933   0.756638
glyburide                  0.554213   89.534815   9.113063   0.797909
tolbutamide                0.000000   99.977399   0.022601   0.000000
pioglitazone               0.115952   92.799167   6.854942   0.229939
rosiglitazone              0.085490   93.745455   5.994143   0.174911
acarbose                   0.002948   99.697345   0.289881   0.009826
miglitol                   0.004913   99.962659   0.030462   0.001965
troglitazone               0.000000   99.997052   0.002948   0.000000
tolazamide                 0.000000   99.961677   0.037341   0.000983
examide                    0.000000  100.000000   0.000000   0.000000
citoglipton                0.000000  100.000000   0.000000   0.000000
insulin                   12.005974   46.560737  30.313661  11.119627
glyburide-metformin        0.005896   99.306252   0.679991   0.007861
glipizide-metformin        0.000000   99.987226   0.012774   0.000000
glimepiride-pioglitazone   0.000000   99.999017   0.000983   0.000000
metformin-rosiglitazone    0.000000   99.998035   0.001965   0.000000
metformin-pioglitazone     0.000000   99.999017   0.000983   0.000000

In [6]:
drop_drugs = [
    "nateglinide",
    "chlorpropamide",
    "acetohexamide",
    "tolbutamide",
    "acarbose",
    "miglitol",
    "troglitazone",
    "tolazamide",
    "examide",
    "citoglipton",
    "glyburide-metformin",
    "glipizide-metformin",
    "glimepiride-pioglitazone",
    "metformin-rosiglitazone",
    "metformin-pioglitazone"
]

raw_data = raw_data.drop(columns=drop_drugs, inplace=False)
raw_data.head()

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,...,repaglinide,glimepiride,glipizide,glyburide,pioglitazone,rosiglitazone,insulin,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),6,25,1,1,41,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,59,...,No,No,No,No,No,No,Up,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,11,...,No,No,Steady,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),1,1,7,2,44,...,No,No,No,No,No,No,Up,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),1,1,7,1,51,...,No,No,Steady,No,No,No,Steady,Ch,Yes,NO

### Drop outliers

In [7]:
numeric_cols = [
    'time_in_hospital',
    'num_lab_procedures',
    'num_procedures',
    'num_medications',
    'number_outpatient',
    'number_emergency',
    'number_inpatient',
    'number_diagnoses'
]

p = 0.01
lower = raw_data[numeric_cols].quantile(p)
upper = raw_data[numeric_cols].quantile(1 - p)

mask = ((raw_data[numeric_cols] < lower) | (raw_data[numeric_cols] > upper)).any(axis=1)

raw_data = raw_data.loc[~mask].copy()

print(f"Remaining rows after drop: {len(raw_data)}")

Remaining rows after drop: 96573

### Handle identifiers

In [8]:
patient_nbr_is_unique = raw_data["patient_nbr"].is_unique

encounter_id_is_unique = raw_data["encounter_id"].is_unique

print(f"Patient number is unique: {patient_nbr_is_unique}")
print(f"Encounter id is unique: {encounter_id_is_unique}")

Patient number is unique: False
Encounter id is unique: True

In [9]:
dup_ids = raw_data["patient_nbr"][raw_data["patient_nbr"].duplicated()].unique()

duplicate_rows = raw_data[raw_data["patient_nbr"].isin(dup_ids)].sort_values(["patient_nbr"])

duplicate_rows.head(50)

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,...,repaglinide,glimepiride,glipizide,glyburide,pioglitazone,rosiglitazone,insulin,change,diabetesMed,readmitted
4267,24437208,135,Caucasian,Female,[50-60),2,1,1,8,77,...,No,No,No,Down,No,No,Steady,Ch,Yes,<30
4780,26264286,135,Caucasian,Female,[50-60),1,1,7,3,31,...,No,No,No,Steady,No,No,No,Ch,Yes,>30
14180,55533660,1152,AfricanAmerican,Female,[60-70),1,1,7,10,54,...,No,No,No,No,No,No,Steady,No,Yes,>30
24642,83281464,1152,AfricanAmerican,Female,[60-70),1,1,7,12,37,...,No,No,No,No,No,No,Up,Ch,Yes,NO
5953,30180318,1152,AfricanAmerican,Female,[50-60),1,1,7,6,45,...,No,No,No,No,No,No,Down,Ch,Yes,>30
23623,80742510,1152,AfricanAmerican,Female,[60-70),1,1,7,8,30,...,No,No,No,No,No,No,Steady,No,Yes,>30
1164,8380170,1152,AfricanAmerican,Female,[50-60),1,1,7,6,43,...,No,No,No,No,No,No,Steady,No,Yes,>30
19914,70601076,1314,Caucasian,Female,[40-50),1,1,7,3,54,...,No,No,No,No,No,No,Steady,Ch,Yes,NO
19765,70190028,1314,Caucasian,Female,[40-50),1,1,7,1,47,...,No,No,No,No,No,No,Steady,No,Yes,<30
15848,60254142,1314,Caucasian,Female,[40-50),2,1,1,2,50,...,No,No,No,No,No,No,Steady,No,Yes,>30
16105,60892254,5220,Caucasian,Male,[70-80),1,1,7,1,35,...,No,No,No,No,No,No,Steady,No,Yes,NO
14128,55397514,5220,Caucasian,Male,[70-80),2,6,1,8,50,...,No,No,No,No,No,No,Steady,No,Yes,>30
6901,33503946,5220,Caucasian,Male,[70-80),2,1,1,11,65,...,No,No,No,No,No,No,Steady,No,Yes,>30
1083,7981038,5220,Caucasian,Male,[60-70),1,1,7,2,15,...,No,No,No,No,No,No,Steady,No,Yes,>30
2001,12979032,5337,Caucasian,Male,[70-80),3,5,1,7,27,...,No,No,Up,Steady,No,No,Steady,Ch,Yes,>30
2941,18824100,5337,Caucasian,Male,[70-80),2,5,1,4,44,...,No,No,Steady,No,No,No,No,Ch,Yes,NO
23541,80435688,6696,AfricanAmerican,Male,[80-90),1,4,7,7,51,...,No,No,Steady,No,No,No,Steady,Ch,Yes,NO
15980,60553632,6696,AfricanAmerican,Male,[80-90),1,1,7,1,36,...,No,No,Steady,No,No,No,No,No,Yes,>30
20078,71046066,10827,Caucasian,Female,[70-80),1,1,7,4,64,...,No,No,No,No,No,No,No,No,No,NO
18558,67060584,10827,Caucasian,Female,[70-80),2,1,1,2,39,...,No,No,No,No,No,No,No,No,No,>30
7665,35935938,11394,AfricanAmerican,Female,[80-90),1,6,7,7,62,...,No,No,No,Steady,No,No,Steady,Ch,Yes,>30
13674,54021606,11394,AfricanAmerican,Female,[80-90),1,1,7,5,75,...,No,No,No,Steady,No,No,Steady,Ch,Yes,<30
18390,66624354,11394,AfricanAmerican,Female,[80-90),1,6,7,4,47,...,No,No,No,No,No,No,No,No,No,NO
5529,28600458,11511,Caucasian,Male,[70-80),2,1,1,7,65,...,No,No,Steady,No,No,No,No,No,Yes,>30
5123,27315318,11511,Caucasian,Male,[70-80),2,1,1,3,56,...,No,No,Steady,No,No,No,No,No,Yes,<30
5302,27873216,11511,Caucasian,Male,[70-80),1,1,7,3,48,...,No,No,No,No,No,No,No,No,No,<30
7923,36676056,11511,Caucasian,Male,[70-80),2,1,1,13,67,...,No,Steady,No,No,No,No,No,No,Yes,NO
18902,67935924,12447,Caucasian,Female,[70-80),1,1,7,9,58,...,No,No,No,No,No,No,Steady,No,Yes,NO
16346,61518390,12447,Caucasian,Female,[70-80),1,3,7,6,54,...,No,No,No,No,No,No,No,No,No,>30
1309,9170688,12447,Caucasian,Female,[70-80),1,5,7,6,75,...,No,No,No,No,No,Steady,Down,Ch,Yes,>30
318,3247932,12447,Caucasian,Female,[70-80),6,25,7,7,70,...,No,No,No,No,No,Steady,Steady,Ch,Yes,>30
5196,27586146,13041,Caucasian,Female,[60-70),3,1,1,4,23,...,No,No,No,No,No,No,No,No,No,>30
8291,37761462,13041,Caucasian,Female,[60-70),1,1,7,6,64,...,No,No,No,No,No,No,Up,Ch,Yes,>30
3058,19423404,13041,Caucasian,Female,[60-70),3,1,1,4,60,...,No,No,No,No,No,No,Down,Ch,Yes,>30
2529,16429764,13041,Caucasian,Female,[60-70),1,1,7,4,50,...,No,No,No,No,No,No,Steady,No,Yes,<30
630,4971204,13041,Caucasian,Female,[60-70),6,25,7,11,67,...,No,No,No,No,No,No,Up,Ch,Yes,>30
19259,68799558,13041,Caucasian,Female,[60-70),1,1,7,4,67,...,No,No,No,No,No,No,Steady,No,Yes,>30
21385,74513244,13041,Caucasian,Female,[60-70),1,1,7,4,58,...,No,No,No,No,No,No,Steady,No,Yes,NO
2763,17719134,13041,Caucasian,Female,[60-70),1,1,7,3,65,...,No,No,No,No,No,No,Down,Ch,Yes,<30
31576,101303700,16425,AfricanAmerican,Female,[50-60),1,1,6,2,29,...,No,No,No,No,No,No,Steady,No,Yes,>30
34690,108277764,16425,AfricanAmerican,Female,[50-60),1,1,6,5,39,...,No,No,No,No,No,No,Steady,No,Yes,NO
21847,75770136,18765,Caucasian,Male,[70-80),3,1,1,1,46,...,No,No,No,No,No,No,No,No,No,>30
8177,37440660,18765,Caucasian,Male,[70-80),3,1,1,1,39,...,No,No,No,No,No,No,No,No,No,>30
23289,79609722,18765,Caucasian,Male,[70-80),1,1,7,5,61,...,No,No,No,No,No,No,No,No,No,NO
2610,16886208,18765,Caucasian,Male,[70-80),2,1,7,3,34,...,No,No,No,No,No,No,No,No,No,>30
24822,83725614,20232,Caucasian,Male,[80-90),1,6,5,6,49,...,No,No,No,No,No,No,Steady,No,Yes,NO
24179,82170354,20232,Caucasian,Male,[80-90),1,1,7,4,57,...,No,No,No,No,No,No,Steady,No,Yes,<30
375,3590394,20295,Caucasian,Male,[70-80),6,25,1,12,80,...,No,No,No,No,No,No,Steady,No,Yes,>30
7904,36578436,20295,Caucasian,Male,[70-80),1,6,7,8,45,...,No,No,No,No,No,No,Steady,No,Yes,>30
23851,81325128,20997,AfricanAmerican,Female,[60-70),1,1,7,3,47,...,No,No,No,No,No,No,No,No,No,NO

Both the patient number and encounter ID are identifiers. While the patient number may not be unique, the dataset is based on individual encounters, so these features won't contribute to model training and will be dropped.

In [10]:
raw_data = raw_data.drop(columns=["encounter_id"], inplace=False)

raw_data.head()

,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,...,repaglinide,glimepiride,glipizide,glyburide,pioglitazone,rosiglitazone,insulin,change,diabetesMed,readmitted
1,55629189,Caucasian,Female,[10-20),1,1,7,3,59,0,...,No,No,No,No,No,No,Up,Ch,Yes,>30
2,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,11,5,...,No,No,Steady,No,No,No,No,No,Yes,NO
3,82442376,Caucasian,Male,[30-40),1,1,7,2,44,1,...,No,No,No,No,No,No,Up,Ch,Yes,NO
4,42519267,Caucasian,Male,[40-50),1,1,7,1,51,0,...,No,No,Steady,No,No,No,Steady,Ch,Yes,NO
5,82637451,Caucasian,Male,[50-60),2,1,2,3,31,6,...,No,No,No,No,No,No,Steady,No,Yes,>30

### Apply One-Hot Encoding to specific columns

In [11]:
OHE_COLS = [
    "race",
    "gender",
    "max_glu_serum",
    "A1Cresult"
]

raw_data = pd.get_dummies(raw_data, columns=OHE_COLS, drop_first=False, dtype=int)

raw_data.head()

,patient_nbr,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,...,gender_Male,gender_Unknown/Invalid,max_glu_serum_>200,max_glu_serum_>300,max_glu_serum_None,max_glu_serum_Norm,A1Cresult_>7,A1Cresult_>8,A1Cresult_None,A1Cresult_Norm
1,55629189,[10-20),1,1,7,3,59,0,18,0,...,0,0,0,0,1,0,0,0,1,0
2,86047875,[20-30),1,1,7,2,11,5,13,2,...,0,0,0,0,1,0,0,0,1,0
3,82442376,[30-40),1,1,7,2,44,1,16,0,...,1,0,0,0,1,0,0,0,1,0
4,42519267,[40-50),1,1,7,1,51,0,8,0,...,1,0,0,0,1,0,0,0,1,0
5,82637451,[50-60),2,1,2,3,31,6,16,0,...,1,0,0,0,1,0,0,0,1,0

### Apply Ordinal Encoding to specific columns

In [12]:
ordinal_cols = [
    "admission_type_id",
    "discharge_disposition_id",
    "admission_source_id",
]

for col in ordinal_cols:
    raw_data[col] = pd.factorize(raw_data[col])[0]

raw_data[ordinal_cols].head()

   admission_type_id  discharge_disposition_id  admission_source_id
1                  0                         0                    0
2                  0                         0                    0
3                  0                         0                    0
4                  0                         0                    0
5                  1                         0                    1

### Apply Ordinal Encoding to `age`

In [13]:
age_map = {
    "[0-10)":0, "[10-20)":1, "[20-30)":2, "[30-40)":3,
    "[40-50)":4, "[50-60)":5, "[60-70)":6, "[70-80)":7,
    "[80-90)":8, "[90-100)":9
}

raw_data["age"] = raw_data["age"].map(age_map).astype(int)
raw_data.head()

,patient_nbr,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,...,gender_Male,gender_Unknown/Invalid,max_glu_serum_>200,max_glu_serum_>300,max_glu_serum_None,max_glu_serum_Norm,A1Cresult_>7,A1Cresult_>8,A1Cresult_None,A1Cresult_Norm
1,55629189,1,0,0,0,3,59,0,18,0,...,0,0,0,0,1,0,0,0,1,0
2,86047875,2,0,0,0,2,11,5,13,2,...,0,0,0,0,1,0,0,0,1,0
3,82442376,3,0,0,0,2,44,1,16,0,...,1,0,0,0,1,0,0,0,1,0
4,42519267,4,0,0,0,1,51,0,8,0,...,1,0,0,0,1,0,0,0,1,0
5,82637451,5,1,0,1,3,31,6,16,0,...,1,0,0,0,1,0,0,0,1,0

### Apply Ordinal Encoding to drug columns

In [14]:
DRUG_COLS = [
    "metformin","repaglinide","glimepiride","glipizide","glyburide","pioglitazone","rosiglitazone","insulin"
]

for col in DRUG_COLS:
    unique_values_drugs = raw_data[col].unique()
    print(f"{col}: {unique_values_drugs}")

metformin: ['No' 'Steady' 'Up' 'Down']
repaglinide: ['No' 'Up' 'Steady' 'Down']
glimepiride: ['No' 'Steady' 'Down' 'Up']
glipizide: ['No' 'Steady' 'Up' 'Down']
glyburide: ['No' 'Steady' 'Up' 'Down']
pioglitazone: ['No' 'Steady' 'Up' 'Down']
rosiglitazone: ['No' 'Steady' 'Up' 'Down']
insulin: ['Up' 'No' 'Steady' 'Down']

In [15]:
drug_map = {"No":0, "Down":1, "Steady":2, "Up":3}

for col in DRUG_COLS:
    raw_data[col] = raw_data[col].map(drug_map).astype(int)

raw_data.head()

,patient_nbr,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,...,gender_Male,gender_Unknown/Invalid,max_glu_serum_>200,max_glu_serum_>300,max_glu_serum_None,max_glu_serum_Norm,A1Cresult_>7,A1Cresult_>8,A1Cresult_None,A1Cresult_Norm
1,55629189,1,0,0,0,3,59,0,18,0,...,0,0,0,0,1,0,0,0,1,0
2,86047875,2,0,0,0,2,11,5,13,2,...,0,0,0,0,1,0,0,0,1,0
3,82442376,3,0,0,0,2,44,1,16,0,...,1,0,0,0,1,0,0,0,1,0
4,42519267,4,0,0,0,1,51,0,8,0,...,1,0,0,0,1,0,0,0,1,0
5,82637451,5,1,0,1,3,31,6,16,0,...,1,0,0,0,1,0,0,0,1,0

### Apply Binary Encoding to `change` and `diabetesMed`

In [16]:
unique_values_change = raw_data["change"].unique()
print(f"Change: {unique_values_change}")

Change: ['Ch' 'No']

In [17]:
unique_values_diabetesMed = raw_data["diabetesMed"].unique()
print(f"DiabetesMed: {unique_values_diabetesMed}")

DiabetesMed: ['Yes' 'No']

In [18]:
binary_map = {"No":0, "Ch":1, "Yes":1}
raw_data["change"] = raw_data["change"].map(binary_map).astype(int)
raw_data["diabetesMed"] = raw_data["diabetesMed"].map(binary_map).astype(int)

raw_data.head()

,patient_nbr,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,...,gender_Male,gender_Unknown/Invalid,max_glu_serum_>200,max_glu_serum_>300,max_glu_serum_None,max_glu_serum_Norm,A1Cresult_>7,A1Cresult_>8,A1Cresult_None,A1Cresult_Norm
1,55629189,1,0,0,0,3,59,0,18,0,...,0,0,0,0,1,0,0,0,1,0
2,86047875,2,0,0,0,2,11,5,13,2,...,0,0,0,0,1,0,0,0,1,0
3,82442376,3,0,0,0,2,44,1,16,0,...,1,0,0,0,1,0,0,0,1,0
4,42519267,4,0,0,0,1,51,0,8,0,...,1,0,0,0,1,0,0,0,1,0
5,82637451,5,1,0,1,3,31,6,16,0,...,1,0,0,0,1,0,0,0,1,0

### Apply Ordinal Encoding to `readmitted` which is our target variable

In [19]:
unique_values_change = raw_data["readmitted"].unique()
print(f"Readmitted: {unique_values_change}")

Readmitted: ['>30' 'NO' '<30']

In [20]:
readmitted_binary_map = {"NO":0, ">30":0, "<30":1}
raw_data["readmitted"] = raw_data["readmitted"].map(readmitted_binary_map).astype(int)

raw_data.head()

,patient_nbr,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,...,gender_Male,gender_Unknown/Invalid,max_glu_serum_>200,max_glu_serum_>300,max_glu_serum_None,max_glu_serum_Norm,A1Cresult_>7,A1Cresult_>8,A1Cresult_None,A1Cresult_Norm
1,55629189,1,0,0,0,3,59,0,18,0,...,0,0,0,0,1,0,0,0,1,0
2,86047875,2,0,0,0,2,11,5,13,2,...,0,0,0,0,1,0,0,0,1,0
3,82442376,3,0,0,0,2,44,1,16,0,...,1,0,0,0,1,0,0,0,1,0
4,42519267,4,0,0,0,1,51,0,8,0,...,1,0,0,0,1,0,0,0,1,0
5,82637451,5,1,0,1,3,31,6,16,0,...,1,0,0,0,1,0,0,0,1,0

# Map `diag_1` to ICD9

In [21]:
unique_values_diag1 = raw_data["diag_1"].unique()
print(f"Diagnosis 1: {unique_values_diag1}")

Diagnosis 1: ['276' '648' '8' '197' '414' '428' '398' '434' '250.7' '157' '999' '410'
 '682' '402' '737' '572' 'V57' '189' '786' '427' '996' '277' '462' '473'
 '411' '174' '486' '998' '511' '432' '626' '295' '196' '250.6' '618' '182'
 '845' '423' '808' '250.4' '722' '403' '784' '707' '440' '151' '715' '997'
 '198' '564' '812' '38' '590' '556' '578' '433' 'V58' '569' '185' '536'
 '250.32' '255' '250.13' '599' '558' '574' '491' '584' '560' '244'
 '250.03' '577' '730' '188' '824' '250.8' '332' '562' '291' '296' '510'
 '401' '263' '438' '70' '250.02' '493' '642' '625' '571' '738' '593'
 '250.42' '807' '456' '446' '518' '575' '250.41' '820' '515' '780'
 '250.22' '995' '235' '250.82' '721' '787' '162' '724' '282' '250.83'
 'V55' '281' '250.33' '530' '435' '250.12' 'V53' '789' '566' '822'
 '250.11' '191' '557' '733' '455' '711' '482' '202' '280' '553' '225'
 '154' '441' '250.81' '349' nan '962' '592' '507' '386' '156' '200' '728'
 '348' '459' '426' '388' '607' '337' '466' '531' '596' '288' '656' '573'
 '492' '220' '516' '210' '922' '286' '885' '958' '661' '969' '250.93'
 '112' '404' '823' '532' '346' '535' '453' '250' '595' '211' '303'
 '250.01' '852' '218' '782' '540' '457' '285' '431' '340' '514' '550' '54'
 '351' '601' '723' '555' '153' '443' '380' '204' '424' '241' '358' '694'
 '331' '345' '681' '447' '290' '158' '579' '436' '335' '309' '654' '805'
 '799' '292' '183' '78' '851' '458' '586' '311' '892' '305' '293' '415'
 '591' '794' '803' '79' '655' '429' '278' '658' '598' '729' '585' '444'
 '604' '727' '214' '552' '284' '680' '708' '41' '644' '481' '821' '413'
 '416' '437' '968' '756' '632' '359' '275' '512' '781' '368' '522' '825'
 '135' '304' '320' '250.31' '669' '868' '496' '826' '567' '3' '203' '53'
 '251' '565' '161' '495' '49' '250.1' '294' '297' '663' '250.43' '576'
 '355' '850' '287' '250.2' '611' '840' '350' '726' '537' '620' '180' '366'
 '783' '11' '751' '716' '250.3' '199' '464' '580' '836' '664' '813' '966'
 '289' '965' '184' '480' '608' '333' '972' '212' '117' '788' '924' '959'
 '621' '238' '785' '714' '942' '250.23' '710' '47' '933' '508' '478' '844'
 '7' '736' '233' '42' '250.5' '395' '201' '253' '250.92' '600' '494' '39'
 '659' '312' '614' '647' '652' '646' '274' '861' '425' '527' '451' '485'
 '217' '250.53' '442' '970' '193' '160' '322' '581' '475' '623' '374'
 '582' '568' '465' '801' '237' '376' '150' '461' '913' '420' '226' '617'
 '987' '641' '298' '790' '336' '362' '228' '513' '383' '746' '353' '227'
 '911' '506' '873' '155' '860' '534' '802' '141' 'V45' '310' '341' '242'
 '719' '239' '533' '283' '616' '519' '301' 'V66' '5' '989' '230' '385'
 '300' '853' '871' '570' '848' '463' '9' '934' '250.21' '236' '361' '594'
 '501' '810' '421' '643' '430' '528' '205' '791' '983' '992' '490' '396'
 '172' '171' '622' '306' '863' '864' '474' '660' '759' '356' '634' '967'
 '551' '695' '187' '732' '747' '323' '308' '370' '252' '152' '846' '164'
 '365' '718' '48' '266' '720' '94' '344' '797' '170' '878' '977' '904'
 'V56' '882' '843' '709' '973' '454' '686' '487' '229' '991' '483' '357'
 '692' '796' '693' '935' '936' '800' '920' 'V26' '261' '307' '262' '250.9'
 '831' '145' '223' 'V71' '839' '685' 'V54' '35' '34' '179' '964' '136'
 '324' '389' '815' '334' '143' '526' '192' 'V67' '917' '88' '219' '325'
 '792' '717' '994' '990' '793' '207' '637' '195' '373' '847' '827' '31'
 '891' '814' '703' '865' '352' '627' '378' '342' '886' '745' '705' '816'
 '541' '986' '610' '633' '640' '369' '753' '173' '835' '379' '445' '272'
 '382' '588' '945' '619' '881' '394' '250.52' '866' '405' '916' '215'
 '893' '75' '671' '928' '906' '897' '725' '867' '115' '890' '734' '521'
 '674' '470' '834' '146' '696' '524' '691' '384' '142' '879' '250.51'
 '246' '448' '955' '653' '149' '245' '735' '883' '854' '952' '838' '194'
 'V43' '163' '216' '147' '354' '27' '477' '318' '880' '921' '377' '471'
 '683' '175' '602' '982' '706' '375' '417' '131' '347' '870' '862' '82'
 '61' '817' '914' '360' '684' '314' 'V63' '36' '57' '240' '208' '915'
 '980' '971' '795' '988' '452' '963' '327' '731' '842' 'V25' '645' '110'
 '944' '603' '250.91' '665' '923' '412' '363' '957' '976' '698' '299'
 '700' '273' '974' '97' '529' '66' '98' '605' '941' '52' '806' '84' '837'
 '657' '895' '338' '523' '542' '114' '543' '372' 'V70' 'E909' '583' 'V07'
 '422' '615' '397' '279' '500' '903' '919' '875' '381' '804' '704' '23'
 '58' '649' '832' '133' '975' '833' '391' '690' '10' 'V51']

In [22]:
raw_data = raw_data.drop(columns=["diag_2", "diag_3"], inplace=False)

Dropping diag2 and diag3 to focus on diag1, which is the first diagnoses. This is to reduce noise in our model.

### Drop empty `diag_1` columns

In this case we will not do imputation because of the bias that can be introduced and since the number of empty columns aren't a lot.

In [23]:
empty_diag1 = raw_data["diag_1"].isna().sum()

print(f"Empty in diag1: {empty_diag1}")

Empty in diag1: 21

In [24]:
raw_data = raw_data.dropna(subset=["diag_1"])

In [25]:
# Sanity check
print("Empty in diag1:", raw_data["diag_1"].isna().sum())

Empty in diag1: 0

In [26]:
chapters = pd.read_csv("../data/external/icd9_chapters.csv")

In [27]:
def safe_int(x):
    if pd.isna(x):
        return None
    s = str(x).strip().upper().replace("V", "").replace("E", "").replace(".", "")
    try:
        return int(s)
    except ValueError:
        return None

def bucket_icd9(code: str) -> str:
    if pd.isna(code):
        return "Unknown"

    s = str(code).strip().upper()

    # V / E chapters
    if s.startswith("V"):
        return "Supplementary Factors (V)"
    if s.startswith("E"):
        return "External Causes (E)"

    s_digits = re.sub(r"\.", "", s)
    m = re.match(r"^(\d{3})", s_digits)
    if not m:
        return "Unknown"

    three = int(m.group(1))

    # Look up in chapter ranges
    for _, row in chapters.iterrows():
        if row["start_num"] is not None and row["end_num"] is not None:
            if row["start_num"] <= three <= row["end_num"]:
                return row["name"]

    return "Other/Unmapped"

chapters["start_num"] = chapters["start"].apply(safe_int)
chapters["end_num"]   = chapters["end"].apply(safe_int)

c = "diag_1"

raw_data[c + "_grp"] = raw_data[c].apply(bucket_icd9)

In [28]:
raw_data.head()

,patient_nbr,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,...,gender_Unknown/Invalid,max_glu_serum_>200,max_glu_serum_>300,max_glu_serum_None,max_glu_serum_Norm,A1Cresult_>7,A1Cresult_>8,A1Cresult_None,A1Cresult_Norm,diag_1_grp
1,55629189,1,0,0,0,3,59,0,18,0,...,0,0,0,1,0,0,0,1,0,Endocrine/Metabolic/Immunity
2,86047875,2,0,0,0,2,11,5,13,2,...,0,0,0,1,0,0,0,1,0,Pregnancy/Childbirth/Puerperium
3,82442376,3,0,0,0,2,44,1,16,0,...,0,0,0,1,0,0,0,1,0,Unknown
4,42519267,4,0,0,0,1,51,0,8,0,...,0,0,0,1,0,0,0,1,0,Neoplasms
5,82637451,5,1,0,1,3,31,6,16,0,...,0,0,0,1,0,0,0,1,0,Circulatory System

In [29]:
raw_data = raw_data.drop(columns=["diag_1"], inplace=False)

### Apply One-Hot Encoding to diag1_grp

In [30]:
raw_data = pd.get_dummies(
    raw_data,
    columns=["diag_1_grp"],
    prefix="diag1",
    drop_first=False,
    dtype=int
)

raw_data.head()

,patient_nbr,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,...,diag1_Mental/Behavioral,diag1_Musculoskeletal/Connective,diag1_Neoplasms,diag1_Nervous System,diag1_Pregnancy/Childbirth/Puerperium,diag1_Respiratory System,diag1_Skin/Subcutaneous,diag1_Supplementary Factors (V),diag1_Symptoms/Signs/Ill-defined,diag1_Unknown
1,55629189,1,0,0,0,3,59,0,18,0,...,0,0,0,0,0,0,0,0,0,0
2,86047875,2,0,0,0,2,11,5,13,2,...,0,0,0,0,1,0,0,0,0,0
3,82442376,3,0,0,0,2,44,1,16,0,...,0,0,0,0,0,0,0,0,0,1
4,42519267,4,0,0,0,1,51,0,8,0,...,0,0,1,0,0,0,0,0,0,0
5,82637451,5,1,0,1,3,31,6,16,0,...,0,0,0,0,0,0,0,0,0,0

# SANITY CHECKS

### Check if there are any non-numeric columns left

In [31]:
# Sanity check
non_numeric = raw_data.select_dtypes(exclude=["number"]).columns
print("Non-numeric columns:", non_numeric.tolist())

Non-numeric columns: []

### Check if there are any missing value columns left

In [32]:
is_null = raw_data.isna().sum()
print(is_null[is_null > 0])

Series([], dtype: int64)

In [33]:
unknown_cols = [col for col in raw_data.columns if "unknown" in col.lower()]

unknown_counts = raw_data[unknown_cols].sum()

print(unknown_counts)

gender_Unknown/Invalid       3
diag1_Unknown             2495
dtype: int64

### Drop the trivial 3 rows with gender as unknown/invalid

In [34]:
raw_data = raw_data[raw_data["gender_Unknown/Invalid"] == 0]

raw_data = raw_data.drop(columns=["gender_Unknown/Invalid"])

In [35]:
raw_data.to_csv("../data/processed/processed.csv", index=False)